name: Package For ZZL

on:
    push:
      paths:
        - ".github/**"
        - "ZZL_Lib/**"
        - "*.py"
jobs:

  assemble:
    uses: ./.github/workflows/assemble.yml

  pypi-upload:
    runs-on: ubuntu-latest
    name: Make and upload a package to (Test)PyPI
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install setuptools wheel

      - name: Create distribution
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: ZZL Files for ${{ github.sha }}
          path: dist/